### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by GR0ZA** [lab-64/split-the-bill-server#141]
There should be a possibility to end the current user's session.

The simplest solution is probably to add a POST /api/user/logout endpoint that deletes the session_cookie associated with the requester.

**Comment by f-odc** [comment]
We also have to address the issue that invalid cookies (validBefore period is expired) are not deleted in the database. This results in a overfilled database.

**Comment by f-odc** [comment]
> We also have to address the issue that invalid cookies (validBefore period is expired) are not deleted in the database. This results in a overfilled database.

I handle this issue with the commit 96b7389 by updating the auth cookie on a new login if a cookie already exist instead of creating a new one. If no auth cookie exist, a new one will be created. 
We have only one auth cookie per user which is maybe not the best solution but better than having multiple unusable cookies lying in the database.
