### ISSUE TITLE
Ensure consistency on bill update

### ISSUE THREAD

**Issue by GR0ZA** [lab-64/split-the-bill-server#188]

**Comment by f-odc** [comment]
Regarding this issue, i have the following idea:
For our *Update* requests, i recommend would use **Patch-like Updating** and sending only the fields which are really updated by the user. This would allow us to merge two requests which both modify the same database entry. 
In this solutions lists will be still an issue. User A can delete an entry and User B can add an entry. If User B performs his request later, the change from user A will be lost if the whole list will be replaced. So we cannot replace the whole list, the solution for this problem is by including **diffs** of the list to the request. By including diffs and specifying the related operand, we can merge these lists in the backend with ease.

**Comment by GR0ZA** [comment]
I don't quite understand what do you mean with diffs for lists. For me it sounds like a lot of responsibility  is moved to frontend

The idea sounds good, imo it's not something we should deal with rn. But try it out if u like to 😃

**Comment by f-odc** [comment]
Branch **188-consistent-item-contribution** allows to update the requester contribution to all items from a bill. Because only the contribution of the requester is changed, simultaneous contribution changes from other users are not in conflict with each other.
