### ISSUE TITLE
Resolve circular method calls

### ISSUE THREAD

**Issue by f-odc** [lab-64/split-the-bill-server#49]
User has a field Group.
Group has a field User.
If we convert one postgres entity to types we create a circular method call. To convert an User we have to convert the Group as well. Inside the Group we convert the Owner and each Member to types.User.

We have to rethink our design. If we query a user which information do we expect?

Possible Solution:
1) Include only UUIDs for Group, Invitation etc. in the types and expect an new request from the frontend with to query more specific information about the UUID. 

2) Keep only User's relations towards Group, Invitations etc. Querying an user will result in information about groups. Querying an group will only display the UUIDs of the owner and members.

**Comment by GR0ZA** [comment]
Just a quick note: I suggest starting with a minimalist approach, primarily sending UUIDs where detailed information isn't immediately necessary. It's difficult to predict what will be the best fit for our app at this stage. Beginning with a lean approach allows us to fine-tune endpoints later by adding extra information or creating new ones for specific data, rather than creating overly complex DTOs upfront. There may be cases where maintaining 'circular' calls makes more sense.

**Comment by GR0ZA** [comment]
I've been thinking about it some more, and I think it'd be cool to get together as a team to nail down the specifics for our API. It might save us some hassle with reworks in the long run.

**Comment by GR0ZA** [comment]
GroupOutputDTO should return a list of UserOutputDTO
UserOutputDTO should only return the uuids of groups or nothing

**Comment by GR0ZA** [comment]
Seems done for me.
